In [1]:
import pandas as pd

In [4]:
audible=pd.read_csv('audible_uncleaned.csv')

In [5]:
audible

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

# About Dataset
- Introduction
- With the trend toward audiobooks growing, I gathered this data to understand how the audiobook market has been growing over the years. From authors of audiobooks to release dates, the data represents the important details of audiobooks from 1998 till 2025 (pre-planned releases).

- I have yet to find a great audiobooks dataset and hence the urge to make a dataset that provides us with information on the basics and the history of audiobooks. I look to improve the dataset with more details in the near future.

# Column Breakdown
- name: Name of the audiobook
- author: Author of the audiobook
- narrator: Narrator of the audiobook
- time: Length of the audiobook
- releasedate: Release date of the audiobook
- language: Language of the audiobook
- stars: No. of stars the audiobook received
- price: Price of the audiobook in INR
- ratings: No. of reviews received by the audiobook

# Issues with dataset


## Manual assesment and automatic assesment

# Quality issues
- incorrect datatype assigned to time,releasedate,price `validity`
- in column author "written by:" is written in each cell `consistency`
- in column narrator "Narratedby:" is written in each cell `consistency`
- price needs to mentioned in inr `accuracy`
- time needs to be in minutes or hours `accuracy`
- "Not rated yet" in stars column instead of 0 or Nan `completness`
- some values in language column are in lower case `consistency`
- "out of" and  "stars" in starts column needs to be removed `consistency`
- duplicate entries are there with same name, author, narrator,language `validity`
- name in author and narrator there is no space between surname and first name `Consistency`
- "Narratedby:anonymous" is there in the narrator column `completness`
- "Writtenby:anonymous" is there in author column `completness`
- 'Free' mentioned in some places in price column `consistency`

# Tidiness issues
- stars column data needs to be distributed in stars and ratings column

In [6]:
audible.duplicated(subset=['name','author','narrator','language']).sum()

398

In [7]:
audible.isnull().sum()

name           0
author         0
narrator       0
time           0
releasedate    0
language       0
stars          0
price          0
dtype: int64

In [8]:
audible.describe()

,name,author,narrator,time,releasedate,language,stars,price
count,87489,87489,87489,87489,87489,87489,87489,87489
unique,82767,48374,29717,2284,5058,36,665,1011
top,The Art of War,"Writtenby:矢島雅弘,石橋遊",Narratedby:anonymous,2 mins,16-05-18,English,Not rated yet,586.00
freq,20,874,1034,372,773,61884,72417,5533

# creating a copy of the dataset

In [9]:
audible_df=audible.copy()

## Cleaning the data

- Completness issues first

In [ ]:
#code
audible_df['stars']=audible_df['stars'].replace('Not rated yet','0')

In [ ]:
# test
audible_df.sample(10)

- removing anonymous with no data avaliable

In [12]:
audible_df['author']=audible_df['author'].replace('Writtenby:Anonymous','No Data Avaliable')
audible_df['author']=audible_df['author'].replace('Writtenby:anonymous','No Data Avaliable')
audible_df['narrator']=audible_df['narrator'].replace('Narratedby:anonymous','No Data Avaliable')
audible_df['narrator']=audible_df['narrator'].replace('Narratedby:Anonymous','No Data Avaliable')

In [13]:
audible_df[audible_df['narrator']=='No Data Avaliable']

,name,author,narrator,time,releasedate,language,stars,price
193,Swamp Sting!,"Writtenby:SebastianFacio,BlakeA.Hoena",No Data Avaliable,11 mins,16-03-22,English,0,105.00
723,The Aeneid,"Writtenby:DiegoAgrimbau,MarceloSosa,TrustedTra...",No Data Avaliable,33 mins,16-03-22,English,0,82.00
724,Nuclear Distraction,"Writtenby:ChrisEverheart,ArcanaStudio",No Data Avaliable,14 mins,16-03-22,English,0,140.00
725,Beauty and the Dreaded Sea Beast,"Writtenby:OtisFrampton,LouiseSimonson",No Data Avaliable,14 mins,16-03-22,English,0,82.00
726,Double Trouble,"Writtenby:ScottNickel,SteveHarpster",No Data Avaliable,6 mins,16-03-22,English,0,105.00
...,...,...,...,...,...,...,...,...
31675,Twelve Steps and Twelve Traditions,No Data Avaliable,No Data Avaliable,5 hrs and 17 mins,23-01-21,English,0,209.00
37316,The Election of 1860,Writtenby:JessicaGunderson,No Data Avaliable,41 mins,21-02-22,English,0,117.00
37701,Georgia,"Writtenby:BridgetParker,JasonKirchner",No Data Avaliable,13 mins,18-03-22,English,0,93.00
47176,Nandhi (Tamil Edition),Writtenby:P.Mathiyalagan,No Data Avaliable,1 hr and 51 mins,14-02-22,tamil,0,48.00
80928,Simple Bike Maintenance,Writtenby:LisaJ.Amstutz,No Data Avaliable,2 mins,21-02-22,English,0,82.00

## Tidiness issue

In [14]:
audible_df['stars1']=audible_df['stars'].str.split('stars').str.get(0)
audible_df['rating']=audible_df['stars'].str.split('stars').str.get(1)

In [15]:
audible_df.drop(columns='stars',inplace=True)
audible_df.rename(columns={'stars1':'stars'},inplace=True)

In [16]:
audible_df

,name,author,narrator,time,releasedate,language,price,stars,rating
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,468.00,5 out of 5,34 ratings
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,820.00,4.5 out of 5,41 ratings
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,410.00,4.5 out of 5,38 ratings
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,615.00,4.5 out of 5,12 ratings
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,820.00,4.5 out of 5,181 ratings
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,596.00,0,NaN
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,820.00,0,NaN
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,938.00,0,NaN
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,680.00,0,NaN
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,569.00,0,NaN

## Validity issues

- duplicate entries are there with same name, author, narrator,language

In [17]:
audible_df.duplicated(subset=['name','author','narrator','language']).sum()

398

In [18]:
audible_df.drop_duplicates(subset=(['name','author','narrator','language']),inplace=True)

In [19]:
audible_df.duplicated(subset=['name','author','narrator','language']).sum()

0

In [20]:
audible_df

,name,author,narrator,time,releasedate,language,price,stars,rating
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,468.00,5 out of 5,34 ratings
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,820.00,4.5 out of 5,41 ratings
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,410.00,4.5 out of 5,38 ratings
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,615.00,4.5 out of 5,12 ratings
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,820.00,4.5 out of 5,181 ratings
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,596.00,0,NaN
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,820.00,0,NaN
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,938.00,0,NaN
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,680.00,0,NaN
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,569.00,0,NaN

## Accuracy issues
- price needs to mentioned in inr

In [21]:
audible_df.sample(5)

,name,author,narrator,time,releasedate,language,price,stars,rating
52470,Zwei wie wir,"Writtenby:NormFoster,RenéHeinersdorff",Narratedby:DanaGolombekvonSenden,1 hr and 15 mins,17-02-22,german,233.00,0,NaN
46332,A Bound Woman is a Dangerous Thing,Writtenby:DaMarisB.Hill,Narratedby:MiaEllis,1 hr and 59 mins,26-03-19,English,227.00,0,NaN
67367,The Lone Assassin,"Writtenby:HelmutOrtner,BenjaminRoss-translator",Narratedby:TraberBurns,6 hrs and 29 mins,23-02-13,English,668.00,0,NaN
28188,El Octavo Habito De la Efectividad a la Grande...,Writtenby:StephenR.Covey,Narratedby:AlejoFelipe,2 hrs and 21 mins,09-01-08,spanish,585.00,0,NaN
82484,As Far as You'll Take Me,Writtenby:PhilStamper,"Narratedby:MichaelCrouch,PhilStamper",8 hrs and 37 mins,09-02-21,English,"1,156.00",0,NaN

In [22]:
audible_df=audible_df.rename(columns={'price':'price(in INR)'})

In [23]:
audible_df

,name,author,narrator,time,releasedate,language,price(in INR),stars,rating
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,468.00,5 out of 5,34 ratings
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,820.00,4.5 out of 5,41 ratings
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,410.00,4.5 out of 5,38 ratings
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,615.00,4.5 out of 5,12 ratings
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,820.00,4.5 out of 5,181 ratings
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,596.00,0,NaN
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,820.00,0,NaN
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,938.00,0,NaN
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,680.00,0,NaN
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,569.00,0,NaN

- time needs to be in minutes or hours

In [24]:
import re
def to_minutes(x):
    x = str(x).lower()
    if "less than 1 min" in x:
        return 0
    
    # Extract hours and minutes using regex
    h_match = re.search(r'(\d+)\s*hr', x)
    m_match = re.search(r'(\d+)\s*min', x)
    
    hours = int(h_match.group(1)) if h_match else 0
    minutes = int(m_match.group(1)) if m_match else 0
    
    return hours*60 + minutes
audible_df["time_mins"] = audible_df["time"].apply(to_minutes)

In [25]:
audible_df.drop(columns='time',inplace=True)
audible_df.rename(columns={'time_mins':'time(mins)'},inplace=True)

In [26]:
audible_df

,name,author,narrator,releasedate,language,price(in INR),stars,rating,time(mins)
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,04-08-08,English,468.00,5 out of 5,34 ratings,140
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,01-05-18,English,820.00,4.5 out of 5,41 ratings,788
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,06-11-20,English,410.00,4.5 out of 5,38 ratings,123
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,05-10-21,English,615.00,4.5 out of 5,12 ratings,676
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,13-01-10,English,820.00,4.5 out of 5,181 ratings,600
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,09-03-17,English,596.00,0,NaN,454
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,21-02-17,English,820.00,0,NaN,607
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,30-12-16,English,938.00,0,NaN,1144
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,23-02-11,English,680.00,0,NaN,248
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,07-03-17,English,569.00,0,NaN,361

## Consistency issue
- some values in language column are in lower case 
- "out of" and  "stars" in starts column needs to be removed 
- ratings written in column ratings algonside numerical values

In [27]:
audible_df.sample(5)

,name,author,narrator,releasedate,language,price(in INR),stars,rating,time(mins)
57512,Auctions,"Writtenby:TimothyP.Hubbard,HarryJ.Paarsch",Narratedby:SeanPratt,29-01-16,English,703.00,0,NaN,340
61399,僕が親ならこう育てるね,Writtenby:ひろゆき,Narratedby:中川典,10-12-21,japanese,697.00,0,NaN,249
79921,Сказки старого Вильнюса III,Writtenby:МаксФрай,Narratedby:ВладимирОвуор,28-01-22,russian,200.00,0,NaN,685
23522,Song for the Blue Ocean,Writtenby:CarlSafina,Narratedby:ToddMcLaren,24-02-13,English,"1,170.00",0,NaN,1467
12826,Learn Spanish - Level 2: Absolute Beginner Spa...,Writtenby:InnovativeLanguageLearning,Narratedby:SpanishPod101.com,07-12-10,English,469.00,0,NaN,281

In [28]:
audible_df['language']=audible_df['language'].str.title()

In [29]:
audible_df.sample(5)

,name,author,narrator,releasedate,language,price(in INR),stars,rating,time(mins)
81740,Girls Who Green the World,Writtenby:DianaKapp,Narratedby:BrittanyPressley,05-04-22,English,"1,256.00",0,NaN,451
37353,The Wheel of Time,Writtenby:CarlosCastaneda,Narratedby:LuisMoreno,31-10-19,English,351.00,5 out of 5,4 ratings,142
2850,American Latin Music,Writtenby:MattDoeden,Narratedby:Intuitive,18-04-17,English,469.00,0,NaN,67
56899,Die Nullzinsfalle,"Writtenby:RonaldStöferle,RahimTaghizadegan,Gre...",Narratedby:PeterWolter,03-09-20,German,602.00,0,NaN,480
30104,The Nature of Nature,Writtenby:EnricSala,Narratedby:WillDamron,28-10-20,English,657.00,4.5 out of 5,2 ratings,382

In [30]:
audible_df['stars']=audible_df['stars'].str.split('out').str.get(0)

In [31]:
audible_df.sample(5)

,name,author,narrator,releasedate,language,price(in INR),stars,rating,time(mins)
60297,Shop Till You Drop,Writtenby:ElaineViets,Narratedby:SarahPesek,28-08-21,English,516.00,0,NaN,573
58951,Emprendedor,Writtenby:ValentínLópez,Narratedby:ValentínLópez,09-11-20,Spanish,233.00,0,NaN,36
46227,Finding Kennedy,Writtenby:JacintaHoward,"Narratedby:JakobiDiem,WesleighSiobhan",19-11-19,English,703.00,0,NaN,654
11884,Chicken Soup for the Soul: Campus Chronicles,"Writtenby:JackCanfield,MarkVictorHansen,AmyNew...","Narratedby:SarahGrace,MacLeodAndrews",20-08-11,English,603.00,0,NaN,586
69727,How to Use Your Healing Power,Writtenby:Dr.JosephMurphy,Narratedby:SeanPratt,09-09-16,English,469.00,0,NaN,212

In [32]:
audible_df['rating']=audible_df['rating'].str.split('ratings').str.get(0)

In [33]:
audible_df['rating']=audible_df['rating'].str.split('rating').str.get(0)

In [34]:
audible_df['rating']=audible_df['rating'].fillna(0)

In [35]:
audible_df

,name,author,narrator,releasedate,language,price(in INR),stars,rating,time(mins)
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,04-08-08,English,468.00,5,34,140
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,01-05-18,English,820.00,4.5,41,788
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,06-11-20,English,410.00,4.5,38,123
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,05-10-21,English,615.00,4.5,12,676
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,13-01-10,English,820.00,4.5,181,600
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,09-03-17,English,596.00,0,0,454
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,21-02-17,English,820.00,0,0,607
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,30-12-16,English,938.00,0,0,1144
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,23-02-11,English,680.00,0,0,248
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,07-03-17,English,569.00,0,0,361

- in column author "written by:" is written in each cell
- in column narrator "Narratedby:" is written in each cell
- 'Free' mentioned in some places in price column

In [36]:
audible_df['author']=audible_df['author'].str.split('Writtenby:').str.get(1)
audible_df['narrator']=audible_df['narrator'].str.split('Narratedby:').str.get(1)

In [37]:
audible_df

,name,author,narrator,releasedate,language,price(in INR),stars,rating,time(mins)
0,Geronimo Stilton #11 & #12,GeronimoStilton,BillLobely,04-08-08,English,468.00,5,34,140
1,The Burning Maze,RickRiordan,RobbieDaymond,01-05-18,English,820.00,4.5,41,788
2,The Deep End,JeffKinney,DanRussell,06-11-20,English,410.00,4.5,38,123
3,Daughter of the Deep,RickRiordan,SoneelaNankani,05-10-21,English,615.00,4.5,12,676
4,"The Lightning Thief: Percy Jackson, Book 1",RickRiordan,JesseBernstein,13-01-10,English,820.00,4.5,181,600
...,...,...,...,...,...,...,...,...,...
87484,Last Days of the Bus Club,ChrisStewart,ChrisStewart,09-03-17,English,596.00,0,0,454
87485,The Alps,StephenO'Shea,RobertFass,21-02-17,English,820.00,0,0,607
87486,The Innocents Abroad,MarkTwain,FloGibson,30-12-16,English,938.00,0,0,1144
87487,A Sentimental Journey,LaurenceSterne,AntonLesser,23-02-11,English,680.00,0,0,248
87488,Havana,MarkKurlansky,FleetCooper,07-03-17,English,569.00,0,0,361

In [38]:
audible_df['price(in INR)']=audible_df['price(in INR)'].replace('Free','0')

In [39]:
audible_df[audible_df['price(in INR)']=='Free']

Empty DataFrame
Columns: [name, author, narrator, releasedate, language, price(in INR), stars, rating, time(mins)]
Index: []

- name in author and narrator there is no space between surname and first name

In [40]:
def split_names(val):
    # Handle NaN or blank values
    if pd.isna(val) or str(val).strip() == "":
        return val  
    
    val = str(val)  # make sure it's a string
    parts = val.split(",")
    cleaned_parts = []
    for p in parts:
        # insert space before capital letters (CamelCase → Camel Case)
        name = re.sub(r'(?<!^)(?=[A-Z])', ' ', p).strip()
        cleaned_parts.append(name)
    return ", ".join(cleaned_parts)

audible_df["narrator"] = audible_df["narrator"].apply(split_names)
audible_df["author"] = audible_df["author"].apply(split_names)

In [41]:
# replacing blank spaces in author and narrator column with no data avaliable
audible_df["author"] = audible_df["author"].replace(r'^\s*$', "No data available", regex=True)
audible_df["narrator"] = audible_df["narrator"].replace(r'^\s*$', "No data available", regex=True)

In [42]:
audible_df.sample(5)

,name,author,narrator,releasedate,language,price(in INR),stars,rating,time(mins)
9906,Otto ja Dracon siepparit,Tapani Bagge,Valtteri Lehtinen,17-02-22,Finnish,166.00,0,0,254
4204,Step by Step 2 (Spanish Edition),"Alison Lanthorn, Shelley Bolles","Alison Lanthorn, Shelley Bolles",24-09-20,Spanish,115.00,0,0,46
29423,The Mental Game of Trading,Jared Tendler,Jared Tendler,26-04-21,English,668.00,4.5,8,584
41074,The War Queens,"Jonathan W. Jordan, Emily Anne Jordan",Hillary Huber,10-03-20,English,937.00,0,0,929
46674,Aristotle's Poetics,Aristotle,Ray Childs,04-04-16,English,351.00,4,1,84

# last validity issue
- incorrect datatype assigned to releasedate,price,stars,rating

In [43]:
audible_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87091 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           87091 non-null  object
 1   author         87074 non-null  object
 2   narrator       85899 non-null  object
 3   releasedate    87091 non-null  object
 4   language       87091 non-null  object
 5   price(in INR)  87091 non-null  object
 6   stars          87091 non-null  object
 7   rating         87091 non-null  object
 8   time(mins)     87091 non-null  int64
dtypes: int64(1), object(8)
memory usage: 6.6+ MB

In [44]:
audible_df['price(in INR)']=audible_df['price(in INR)'].replace(",", "", regex=True).astype('float')
audible_df['stars']=audible_df['stars'].astype('float')
audible_df['rating']=audible_df['rating'].replace(",", "", regex=True).astype('int')
audible_df['releasedate']=pd.to_datetime(audible_df['releasedate'])

/tmp/ipykernel_639/4193765154.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  audible_df['releasedate']=pd.to_datetime(audible_df['releasedate'])

In [45]:
audible_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87091 entries, 0 to 87488
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           87091 non-null  object
 1   author         87074 non-null  object
 2   narrator       85899 non-null  object
 3   releasedate    87091 non-null  datetime64[ns]
 4   language       87091 non-null  object
 5   price(in INR)  87091 non-null  float64
 6   stars          87091 non-null  float64
 7   rating         87091 non-null  int64
 8   time(mins)     87091 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 6.6+ MB

In [46]:
audible_df.to_csv('audible_cleaned.csv')

PermissionError: [Errno 13] Permission denied: 'audible_cleaned.csv'

In [47]:
audible_df.describe()

,releasedate,price(in INR),stars,rating,time(mins)
count,87091,87091.000000,87091.000000,87091.000000,87091.000000
mean,2018-06-26 03:46:26.340724224,558.940337,0.765200,3.376675,417.365411
min,1998-12-27 00:00:00,0.000000,0.000000,0.000000,0.000000
25%,2016-09-08 00:00:00,268.000000,0.000000,0.000000,142.000000
50%,2020-01-31 00:00:00,585.000000,0.000000,0.000000,386.000000
75%,2021-08-04 00:00:00,755.000000,0.000000,0.000000,584.000000
max,2025-11-14 00:00:00,7198.000000,5.000000,12569.000000,8595.000000
std,NaN,336.006195,1.707368,71.814930,364.497203